// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package payment

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%.2f EUR":                16,
	"Account holder":          11,
	"Amount":                  15,
	"BIC (if required)":       13,
	"Bank name (if required)": 14,
	"Cash":                    2,
	"IBAN":                    12,
	"If you use TOR or a VPN: The payment options displayed depend on the country of your IP address. In addition, PayPal blocks some TOR exit nodes. In that case, try „New Circuit for this Site“.":                                                                                                        9,
	"Make a SEPA (Single Euro Payments Area) bank transfer to our German bank account. We manually check for new incoming payments every day. We will see your name and bank account number on our account statement. If you are making an international wire transfer, please select the „OUR“ fee option.": 10,
	"Monero or Bitcoin":           0,
	"Pay using Monero or Bitcoin": 5,
	"Pay with Monero (XMR) or Bitcoin (BTC). The full amount must be paid with a single transaction to the given address within 60 minutes. If your payment arrives too late, we have to confirm it manually. If in doubt, please contact us.": 4,
	"Please include a note with this order number": 7,
	"Purpose":            17,
	"SEPA Bank Transfer": 3,
	"Send cash in an insured letter or package to our store address in Germany. After we take out the money, we shred the letter. Please check the cash shipment limits of your postal company (e. g. Deutsche Post „Einschreiben Wert“ up to 100 Euros within Germany, DHL Parcel up to 500 Euros). Send it to:": 6,
	"We only send the order number to PayPal. Your ordered items and delivery or pickup details will not be sent to PayPal.": 8,
	"btcpay:en": 1,
}

var de_DEIndex = []uint32{ // 19 elements
	0x00000000, 0x00000014, 0x00000021, 0x00000029,
	0x0000003f, 0x0000016c, 0x00000192, 0x000002d5,
	0x00000307, 0x000003a0, 0x0000049a, 0x000005d4,
	0x000005e1, 0x000005e6, 0x000005f9, 0x0000060d,
	0x00000614, 0x0000061d, 0x00000630,
} // Size: 100 bytes

const de_DEData string = "" + // Size: 1584 bytes
	"\x02Monero oder Bitcoin\x02btcpay:de-DE\x02Bargeld\x02SEPA-Banküberweisu" +
	"ng\x02Bezahle den angegebenen Betrag in Monero (XMR) oder Bitcoin (BTC)." +
	" Der Betrag muss innerhalb von 60 Minuten vollständig und als einzelne T" +
	"ransaktion auf der angegebenen Adresse eingehen. Falls deine Zahlung ver" +
	"spätet eintrifft, müssen wir sie manuell bestätigen. Im Zweifel kontakti" +
	"ere uns bitte.\x02Zur Bezahlung mit Monero oder Bitcoin\x02Sende uns Bar" +
	"geld in einem versichertem Brief oder Paket. Nachdem wir das Geld entnom" +
	"men haben, schreddern wir den Brief. Bitte beachte die Höchstgrenzen dei" +
	"nes Postunternehmens für den Bargeldversand (z. B. Deutsche Post „Einsch" +
	"reiben Wert“ bis 100 Euro innerhalb Deutschlands, DHL Paket bis 500 Euro" +
	"). Sende es an:\x02Bitte lege einen Zettel mit der Bestellnummer bei\x02" +
	"Wir übermitteln nur die Bestellnummer an PayPal. Deine bestellten Artike" +
	"l sowie die Details zu Lieferung oder Abholung werden nicht an PayPal ge" +
	"sendet.\x02Falls du TOR oder einen VPN benutzt: Die angezeigten Bezahlmö" +
	"glichkeiten sind von der Länderzuordnung deiner IP-Adresse abhängig. Dar" +
	"über hinaus blockiert PayPal manche TOR Exit Nodes. In dem Fall versuch" +
	"e es mit „New Circuit for this Site“.\x02Führe eine SEPA-Überweisung (ei" +
	"nheitlicher Euro-Zahlungsverkehrsraum) auf unser deutsches Bankkonto aus" +
	". Wir prüfen es täglich manuell auf neue Zahlungseingänge. Wir werden de" +
	"inen Namen und deine IBAN auf unserem Kontoauszug sehen. Bei einer Ausla" +
	"ndsüberweisung wähle bitte die Gebührenregelung „OUR“.\x02Kontoinhaber" +
	"\x02IBAN\x02BIC (falls nötig)\x02Bank (falls nötig)\x02Betrag\x02%.2f €" +
	"\x02Überweisungszweck"

var en_USIndex = []uint32{ // 19 elements
	0x00000000, 0x00000012, 0x0000001c, 0x00000021,
	0x00000034, 0x0000011d, 0x00000139, 0x00000269,
	0x00000296, 0x0000030d, 0x000003d1, 0x000004fc,
	0x0000050b, 0x00000510, 0x00000522, 0x0000053a,
	0x00000541, 0x0000054a, 0x00000552,
} // Size: 100 bytes

const en_USData string = "" + // Size: 1362 bytes
	"\x02Monero or Bitcoin\x02btcpay:en\x02Cash\x02SEPA Bank Transfer\x02Pay " +
	"with Monero (XMR) or Bitcoin (BTC). The full amount must be paid with a " +
	"single transaction to the given address within 60 minutes. If your payme" +
	"nt arrives too late, we have to confirm it manually. If in doubt, please" +
	" contact us.\x02Pay using Monero or Bitcoin\x02Send cash in an insured l" +
	"etter or package to our store address in Germany. After we take out the " +
	"money, we shred the letter. Please check the cash shipment limits of you" +
	"r postal company (e. g. Deutsche Post „Einschreiben Wert“ up to 100 Euro" +
	"s within Germany, DHL Parcel up to 500 Euros). Send it to:\x02Please inc" +
	"lude a note with this order number\x02We only send the order number to P" +
	"ayPal. Your ordered items and delivery or pickup details will not be sen" +
	"t to PayPal.\x02If you use TOR or a VPN: The payment options displayed d" +
	"epend on the country of your IP address. In addition, PayPal blocks some" +
	" TOR exit nodes. In that case, try „New Circuit for this Site“.\x02Make " +
	"a SEPA (Single Euro Payments Area) bank transfer to our German bank acco" +
	"unt. We manually check for new incoming payments every day. We will see " +
	"your name and bank account number on our account statement. If you are m" +
	"aking an international wire transfer, please select the „OUR“ fee option" +
	".\x02Account holder\x02IBAN\x02BIC (if required)\x02Bank name (if requir" +
	"ed)\x02Amount\x02%.2f EUR\x02Purpose"

	// Total table size 3146 bytes (3KiB); checksum: 270F5798
