// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package countries

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"de_DE": &dictionary{index: de_DEIndex, data: de_DEData},
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Austria":        0,
	"Belgium":        1,
	"Bulgaria":       2,
	"Croatia":        14,
	"Cyprus":         4,
	"Czechia":        5,
	"Denmark":        7,
	"Estonia":        8,
	"Finland":        10,
	"France":         11,
	"Germany":        6,
	"Greece":         13,
	"Hungary":        15,
	"Ireland":        16,
	"Italy":          17,
	"Latvia":         20,
	"Lithuania":      18,
	"Luxembourg":     19,
	"Malta":          21,
	"Netherlands":    22,
	"Poland":         23,
	"Portugal":       24,
	"Romania":        25,
	"Slovakia":       28,
	"Slovenia":       27,
	"Spain":          9,
	"Sweden":         26,
	"Switzerland":    3,
	"United Kingdom": 12,
}

var de_DEIndex = []uint32{ // 30 elements
	0x00000000, 0x0000000c, 0x00000014, 0x0000001e,
	0x00000026, 0x0000002d, 0x00000038, 0x00000044,
	0x0000004e, 0x00000056, 0x0000005e, 0x00000067,
	0x00000072, 0x0000008a, 0x00000097, 0x000000a0,
	0x000000a7, 0x000000ae, 0x000000b6, 0x000000be,
	0x000000c8, 0x000000d1, 0x000000d7, 0x000000e3,
	0x000000e9, 0x000000f2, 0x000000fc, 0x00000105,
	0x0000010f, 0x00000118,
} // Size: 144 bytes

const de_DEData string = "" + // Size: 280 bytes
	"\x02Österreich\x02Belgien\x02Bulgarien\x02Schweiz\x02Zypern\x02Tschechie" +
	"n\x02Deutschland\x02Dänemark\x02Estland\x02Spanien\x02Finnland\x02Frankr" +
	"eich\x02Vereinigtes Königreich\x02Griechenland\x02Kroatien\x02Ungarn\x02" +
	"Irland\x02Italien\x02Litauen\x02Luxemburg\x02Lettland\x02Malta\x02Nieder" +
	"lande\x02Polen\x02Portugal\x02Rumänien\x02Schweden\x02Slowenien\x02Slowa" +
	"kei"

var en_USIndex = []uint32{ // 30 elements
	0x00000000, 0x00000008, 0x00000010, 0x00000019,
	0x00000025, 0x0000002c, 0x00000034, 0x0000003c,
	0x00000044, 0x0000004c, 0x00000052, 0x0000005a,
	0x00000061, 0x00000070, 0x00000077, 0x0000007f,
	0x00000087, 0x0000008f, 0x00000095, 0x0000009f,
	0x000000aa, 0x000000b1, 0x000000b7, 0x000000c3,
	0x000000ca, 0x000000d3, 0x000000db, 0x000000e2,
	0x000000eb, 0x000000f4,
} // Size: 144 bytes

const en_USData string = "" + // Size: 244 bytes
	"\x02Austria\x02Belgium\x02Bulgaria\x02Switzerland\x02Cyprus\x02Czechia" +
	"\x02Germany\x02Denmark\x02Estonia\x02Spain\x02Finland\x02France\x02Unite" +
	"d Kingdom\x02Greece\x02Croatia\x02Hungary\x02Ireland\x02Italy\x02Lithuan" +
	"ia\x02Luxembourg\x02Latvia\x02Malta\x02Netherlands\x02Poland\x02Portugal" +
	"\x02Romania\x02Sweden\x02Slovenia\x02Slovakia"

	// Total table size 812 bytes (0KiB); checksum: 5D1D57B9
